---
swagger: "2.0"
info:
  description: "Web-Shiori API document"
  version: "1.0.0"
  title: "Web-Shiori API"
host: "web-shiori-api-document.herokuapp.com"
tags:
- name: "auth"
  description: "認証関連API"
- name: "content"
  description: "コンテンツ関連API"
- name: "folder"
  description: "フォルダ関連API"
schemes:
- "https"
paths:
  /v1/auth:
    post:
      tags:
      - "auth"
      summary: "会員登録用API"
      description: "会員登録します。\n email, password, password_confirmationをリクエストで受け取り、ユ\
        ーザと認証用のトークンを生成します。"
      operationId: "v1AuthPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request Body"
        required: true
        schema:
          $ref: "#/definitions/AuthRequest"
      responses:
        "200":
          description: "A successful response."
          headers:
            access-token:
              type: "string"
              description: "access-token"
            client:
              type: "string"
              description: "client"
            uid:
              type: "string"
              description: "uid"
          schema:
            $ref: "#/definitions/AuthResponse"
      x-swagger-router-controller: "Auth"
definitions:
  AuthRequest:
    type: "object"
    properties:
      email:
        type: "string"
        description: "メールアドレス"
      password:
        type: "string"
        description: "パスワード"
      password_confirmation:
        type: "string"
        description: "パスワード(確認用)"
    example:
      password: "password"
      password_confirmation: "password_confirmation"
      email: "email"
  AuthResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
        description: "status"
      data:
        $ref: "#/definitions/User"
    example:
      data:
        uid: "example@example.com"
        updated_at: "2019-05-12T20:48:24.000+09:00"
        provider: "email"
        created_at: "2019-05-12T20:48:24.000+09:00"
        id: 126
        allow_password_change: false
        email: "example2@example.com"
      status: "success"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 126
        description: "ユーザid"
      provider:
        type: "string"
        example: "email"
        description: "provider"
      uid:
        type: "string"
        example: "example@example.com"
        description: "uid"
      allow_password_change:
        type: "boolean"
        example: false
        description: "allow_password_change"
      email:
        type: "string"
        example: "example2@example.com"
        description: "email"
      created_at:
        type: "string"
        example: "2019-05-12T20:48:24.000+09:00"
        description: "created_at"
      updated_at:
        type: "string"
        example: "2019-05-12T20:48:24.000+09:00"
        description: "updated_at"
    example:
      uid: "example@example.com"
      updated_at: "2019-05-12T20:48:24.000+09:00"
      provider: "email"
      created_at: "2019-05-12T20:48:24.000+09:00"
      id: 126
      allow_password_change: false
      email: "example2@example.com"
